### ISSUE TITLE
error on macOS 10.14.6 in terrain tessellation example

### ISSUE THREAD

**Issue by zacharycarter** [KhronosGroup/Vulkan-Samples#186]
I'm encountering the following errors when running the terrain tessellation example (all of the other API examples I've tried have worked without issue.

```
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed:

program_source:101:85: error: as_type cast from 'half' to 'float' is not allowed
                spvTessLevel[gl_PrimitiveID].insideTessellationFactor[0] = half(mix(as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[0]), as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[3]), 0.5));
                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
program_source:101:157: error: as_type cast from 'half' to 'float' is not allowed
                spvTessLevel[gl_PrimitiveID].insideTessellationFactor[0] = half(mix(as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[0]), as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[3]), 0.5));
                                                                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
program_source:102:85: error: as_type cast from 'half' to 'float' is not allowed
                spvTessLevel[gl_PrimitiveID].insideTessellationFactor[1] = half(mix(as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[2]), as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[1]), 0.5));
                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
program_source:102:157: error: as_type cast from 'half' to 'float' is not allowed
                spvTessLevel[gl_PrimitiveID].insideTessellationFactor[1] = half(mix(as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[2]), as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[1]), 0.5));
                                                                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Tessellation control shader function could not be compiled into pipeline. See previous logged error.
[error] [samples/api/terrain_tessellation/terrain_tessellation.cpp:639] Detected Vulkan error: ERROR_INVALID_SHADER_NV
```

Commenting out lines 111 & 112 of the `terrain.tesc` causes the error to disappear - 

```
gl_TessLevelInner[0] = mix(gl_TessLevelOuter[0], gl_TessLevelOuter[3], 0.5);
gl_TessLevelInner[1] = mix(gl_TessLevelOuter[2], gl_TessLevelOuter[1], 0.5);
```

however I'm not sure what the actual fix is.

**Comment by zacharycarter** [comment]
I'm guessing this is due to metal tessellation being totally different and MotlenVK not supporting it. If that's the case - feel free to close this.

**Comment by ghost** [comment]
@billhollings - Is this the case? We expect that it is but would like to confirm directly with you. :)

**Comment by cdavis5e** [comment]
MoltenVK *is* supposed to support tessellation, but there's apparently a bug in SPIRV-Cross.

**Comment by billhollings** [comment]
>MoltenVK is supposed to support tessellation, but there's apparently a bug in SPIRV-Cross.

Thanks, @cdavis5e. Are you going to try to take care of this immediately...or should I create an issue on the SPIRV-Cross site to track this?

**Comment by cdavis5e** [comment]
I'll look into this now.

**Comment by cdavis5e** [comment]
KhronosGroup/SPIRV-Cross#1494

**Comment by ghost** [comment]
@billhollings @cdavis5e - Is this resolved now that 1494 is merged? :)

**Comment by zacharycarter** [comment]
@KhronosKris @billhollings @cdavis5e - I attempted building the project against the `master` branches of `spirv-cross` and `glslang`. I had to remove one `#include` - `#include <glslang/Include/revision.h>` in `glsl_compiler.cpp`.

I still see the same error in the `vulkan_samples` application though:

```
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed: 

program_source:101:85: error: as_type cast from 'half' to 'float' is not allowed
                spvTessLevel[gl_PrimitiveID].insideTessellationFactor[0] = half(mix(as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[0]), as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[3]), 0.5));
                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
program_source:101:157: error: as_type cast from 'half' to 'float' is not allowed
                spvTessLevel[gl_PrimitiveID].insideTessellationFactor[0] = half(mix(as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[0]), as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[3]), 0.5));
                                                                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
program_source:102:85: error: as_type cast from 'half' to 'float' is not allowed
                spvTessLevel[gl_PrimitiveID].insideTessellationFactor[1] = half(mix(as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[2]), as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[1]), 0.5));
                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
program_source:102:157: error: as_type cast from 'half' to 'float' is not allowed
                spvTessLevel[gl_PrimitiveID].insideTessellationFactor[1] = half(mix(as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[2]), as_type<float>(spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[1]), 0.5));
                                                                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.
```

**Comment by cdavis5e** [comment]
I *know* I fixed this. I used the exact source from the sample to make the test case.

What revision of MoltenVK? Did you update `ExternalRevisions/SPIRV-Cross_repo_revision`? The version of SPIRV-Cross that MoltenVK builds against was recently updated; if you didn't use a recent MoltenVK `master`, try updating.

**Comment by zacharycarter** [comment]
@cdavis5e - I'm probably doing something wrong, and please accept my apologies for not being more knowledgeable about this workflow, but I'll outline the steps I took based on your suggestion above:

1) Downloaded the latest VulkanSDK from: https://vulkan.lunarg.com/sdk/home and extracted the contents of the dmg
2) Cloned the MoltenVK repo from: https://github.com/KhronosGroup/MoltenVK
3) Ran `./fetchDependencies --macos` from the MoltenVK project root
4) Built the `MoltenVK Package (macOS only)` scheme in the `MoltenVKPackaging` Xcode project
5) Overwrote the `MoltenVK` directory in the extracted Vulkan SDK with the `MoltenVK` folder found in the `{MoltenVKProjectDir}/Package/Release` directory
6) Ran the `install_vulkan.py` python script in the root of the Vulkan SDK directory

However I'm still running into the same error.

My best guess is that the `Vulkan-Samples` project is linking to libraries included with the Vulkan SDK (in the `macOS/lib` dir) and not to the MoltenVK framework itself. I'll see if I can't get this linking against the MoltenVK framework so I can verify that the issue is addressed by your change.

**Comment by zacharycarter** [comment]
Okay - I was able to get things compiling by moving the `libMoltenVK.dylib` shared library into my `/usr/local/lib` folder after running `sh uninstall.sh` from the root of the Vulkan SDK directory. Apparently volk will load this dylib as a fallback - and now the shader compiles (however nothing is drawn). I can at least verify that this shader compilation issue no longer prevents the example from running. I'll have to dig further to understand why exactly nothing is drawn.

**Comment by zacharycarter** [comment]
Okay - so GLFW was failing to create the Vulkan surface. Creating a symlink to the `libMoltenVK.dylib` at `libvulkan.1.dylib` which is where GLFW searches for the library, fixed the problem. I can confirm that the sample is running as expected now @KhronosKris and the issue can be closed.

**Comment by ghost** [comment]
Thanks all for your efforts to resolve this. :)

**Comment by wasimabbas-arm** [comment]
Perhaps we should be updating our SPIRV-Cross submodule to point to the fix as well.

**Comment by wasimabbas-arm** [comment]
@zacharycarter Why did you have to download MoltenVK separately? The one that comes with the SDK isn't working for you? Or its because it has a bundled SPIRV-Cross that needed updating?

**Comment by zacharycarter** [comment]
@wasimabbas-arm - I didn't have to download it separately, I had to build it and then make sure Volk and glfw were loading symbols from the shared library produced by the build. I don't think the latest published SDK version on LunarG's site includes the aforementioned fix.

I first tried updating the SPIRV-Cross submodule to point to the latest commit in the master branch of SPIRV-Cross and glslang but the shared still fail to compile.

I hope that answers your question - if anything is still not clear I can try to elaborate more.
